### PR TITLE
Implement Group Permission protection using the dropdown option as the Group Check detection

### PR DESCRIPTION
**Pull request by Yippy**
This PR is to allow only specific Group permission to access tag discussion, by reusing Password logic.
image

Within Tag edit modal there is an added protection for the new Group protection checkbox
image
image

Sidebar will have new icon for Group Permission tags.
image

Added new settings options for Tag Passwords extension page.

1. Give Admin a choice to display unlocked icon next to tag name, for notification that these tags are restricted access.
2. Give Admin a choice to hide protected tags from sidebar navigation.
image
image
3. Give Admin a choice to display protected tags within the Tags Page, otherwise it be hidden from User

image
image

### CODE REVIEW

**Comment by datlechin** [comment]
Thank you for submitting the PR.

The current code adds a new field called group to enter the name of the permission group, this is quite difficult to use. It would be better to allow users to select the available permission groups using a dropdown.

**Comment by Yippy** [comment]
chrome-capture-2024-2-19
@datlechin I've implemented a dropdown selection option, the column now store Group IDs as a example '1,4' is for Admin (ID 1) and Mod (ID 4).

I've dropped the column 'group' to 'protected_group_ids'

**Comment by Yippy** [comment]
Adding Permission Group for editing Tag
Here is an example of removing and adding groups

**Comment by Yippy** [comment]
I've amended the protected group, instead of string use JSON instead.
That way it can be future feature proof, if you really wanted you can add a new feature that each of the protected group with an individual password, but just having group detection is suffice for my use case.

**Review by datlechin — APPROVED** [review]
Thank you!

**Comment by datlechin** [comment]
@Yippy can you merge to the `main` branch to resolve the conflict issue

**Comment by Yippy** [comment]
image
Not sure how to fix these conflicts, the PR is for [datlechin:main](https://github.com/datlechin/flarum-tag-passwords/tree/main)

**Comment by Yippy** [comment]
Thanks for merging 😄, I forgot to amend the README to show the new added feature. Seems like a lot of formatting and changes has to be done on your end, thanks again.

**Pull request merged**
