### PR TITLE
Better Restriction for Tag Protected Discussions 

### LINKED ISSUE #12: Hide posts that are from Protected Discussion
This issue is to remind me about the issue of protected post being shown within the User Posts Profile, I will make a new PR to hide this data.

image

### PR DESCRIPTION
**Pull request by Yippy**
Closed #12 #13 

### New Permissions Settings
Toggle user group for each settings, instead of using a on or off switch.
image

### Provide Access for Sharing Link depending on User Roles
**Everyone**
image
**Admin Only**
image

### User Page Post Page is now protected, you can choose to show the protected 
image

### Data API is now restricted for protected Tags
The data is still displaying IDs for objects, but the details are now cleared from view. Please note that API will pretty much strip all data away, unless you are viewing the Discussion Page with the Correct User role for URL Sharing.
image

### CODE REVIEW

**Comment by Yippy** [comment]
Forgot to mentioned that this will fix #12 and #13 Issues.

Should I put myself as a contributor for this extension?

**Comment by datlechin** [comment]
> Should I put myself as a contributor for this extension?

Thank you for your contribution!

It looks great.

I'll go ahead and merge your changes and credit you as the contributor for this extension.

_P.S: For your next PR, you won't need to push files in the `dist` directory, as the bot will handle it for you._

**Comment by Yippy** [comment]
Please wait, I found a bug

**Comment by datlechin** [comment]
I'll mark the PR as a draft. Once you're finished, you can mark it as ready for review.

**Comment by Yippy** [comment]
I've fixed the issue when using Theme extension that doesn't like null string, this is now ready. I haven't updated the dist with the latest changes.

**Comment by Yippy** [comment]
PR is ready, tidied most it now.

**Comment by datlechin** [comment]
Thank you!

**Review by datlechin — APPROVED** [review]

**Pull request merged**
